### ISSUE TITLE
running error: kepler_test

### ISSUE THREAD

**Issue by xiayiyu** [sivaramambikasaran/HODLR#10]
I just begin to try the example for kepler_test.cpp, but it stopped halfway.
Here the error report:
Factoring the matrix...
kepler: /home/yu/下载/eigen-eigen-dd44029906a1/Eigen/src/Core/Redux.h:413: typename Eigen::internal::traits<T>::Scalar Eigen::DenseBase<Derived>::redux(const Func&) const [with BinaryOp = Eigen::internal::scalar_max_op<double, double>; Derived = Eigen::PartialReduxExpr<const Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::Matrix<double, -1, -1> >, Eigen::internal::member_sum<double>, 0>; typename Eigen::internal::traits<T>::Scalar = double]: Assertion `this->rows()>0 && this->cols()>0 && "you are using an empty matrix"' failed.
已放弃 (核心已转储)
Is that my Eigen installing problem?

**Comment by sivaramambikasaran** [comment]
This is fixed now.
