### ISSUE TITLE
clang error [Fixed]

### ISSUE THREAD

**Issue by exoplaneteer** [sivaramambikasaran/HODLR#6]
When installing HODLR on a fresh install of OSX Mavericks, I got this error:

clang: error: -O4 is equivalent to -O3

Google found https://github.com/openMVG/openMVG/issues/102 

The solution is to change line 81 of CMakeLists.txt from "-O4" to "-flto".  Everything else stayed the same.  The issue is the the newest Xcode does not attribute LTO directly with -O4 (I'm paraphrasing the link above).

I was hoping there could be a way for future builds to avoid this issue.

Thank you all the same for a great package

-Jonathan

**Comment by sivaramambikasaran** [comment]
Fixed in #
